### ISSUE TITLE
おしらせのタイトルが「湊のゲストハウス」のままになっている

### ISSUE THREAD

**Issue by ishibashi-futos** [Drop-in-Hachinohe/Dropin#55]
https://dropin8.site/guest_house/news/xstyt5y4md-d

![21EF6117-8518-4961-AB78-45A231160138](https://user-images.githubusercontent.com/41904268/227755985-a14d5dea-c962-41e2-86ed-2d128154c766.png)

**Comment by yuta-sksn** [comment]
microCMS 側でコンテンツの修正対応になりますね。

**Comment by YuukiIshibashi** [comment]
修正します！！

**Comment by YuukiIshibashi** [comment]
修正完了しました！ご指摘ありがとうございますmm
