### ISSUE TITLE
ゲストハウスの「施設」ページを開くと真っ白な画面が開く

### ISSUE THREAD

**Issue by ishibashi-futos** [Drop-in-Hachinohe/Dropin#56]
https://dropin8.site/guest_house/facilities

**Comment by yuta-sksn** [comment]
こちら、`/guest_house/facilities` に該当するルーティングが定義されていないことが原因かと思われます。
現状の対応方法としては、ページを実装するまで該当リンク (34 - 37行目) をコメントアウトするのが良いかと思います👍

https://github.com/Drop-in-Hachinohe/Dropin/blob/c1b282ca5434e275d9a91dc988ba1878e90ef5d0/src/views/GuestHouse/_App.vue#L30-L37

**Comment by yuta-sksn** [comment]
ステージングで動作確認できたので close します！
