### ISSUE TITLE
Wifiのお知らせを作る

### ISSUE THREAD

**Issue by YuukiIshibashi** [Drop-in-Hachinohe/Dropin#58]

**Comment by YuukiIshibashi** [comment]
@TakagiKameko さんありがとうございました!!

![Image](https://github.com/Drop-in-Hachinohe/Dropin/assets/20594454/5e9bdd33-9969-4fbf-b33f-d966fdeec07b)
![Image](https://github.com/Drop-in-Hachinohe/Dropin/assets/20594454/de653211-a8e0-40de-a9e6-11c7a498aedf)

**Comment by TakagiKameko** [comment]
わあ使ってもらえてる！
うれしい😊
