### ISSUE TITLE
PRテンプレート，Issuesテンプレートが欲しい

### ISSUE THREAD

**Issue by ishibashi-futos** [Drop-in-Hachinohe/Dropin#61]
コントリビューターとして，PR, Issuesテンプレートを用意して欲しい
なぜならば，必要なことがあらかじめわかっていると手戻りが少ないからだ

https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by yuta-sksn** [comment]
昔、青森のコロナ特設サイトで使用していた PR テンプレートならあります（普段から使用しております！）
Issue テンプレートはないので、良しなに。。

[PULL_REQUEST_TEMPLATE.md]
```
## 📝 関連する課題 / Related Issues

- [課題番号](課題 URL) 課題名

## ⛏ 変更内容 / Details of Changes

- 

## 📸 スクリーンショット / Screenshots

<details>
<summary>スクリーンショット一覧</summary>

- 

</details>

## 💬 備考 / Remarks

- 

```

こちらのテンプレートでも良ければ .github ディレクトリの作成して `PULL_REQUEST_TEMPLATE.md` を配置 & PR 発行 -> マージで次回から使用できます！🙇‍♂️

**Comment by ishibashi-futos** [comment]
このテンプレート、いいですね（青森コロナ特設サイトかかわってたんですね 😍）。
後でテンプレート作成してPR出しておこう。

**Comment by yuta-sksn** [comment]
こちら、LGTM で merge しました！
